server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3316}/${DB_NAME:trial}
    username: ${DB_USER:docker}
    password: ${DB_USER:docker}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
axon:
  axonserver:
    enabled: false
  serializer:
    general: jackson
    events: jackson
  kafka:
    # 複数プロセスでclient-idが重複しないようにする
    client-id: axon-kafka-trial-consumer-${random.uuid}
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      event-processor-mode: tracking
#      event-processor-mode: subscribing
#    properties:
#      auto.offset.reset: earliest
    default-topic: doc-topic
application:
  kafka:
    topics: doc-topic, default-topic