server:
  port: 8081
axon:
  axonserver:
    enabled: false
  serializer:
    events: jackson
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      event-processor-mode: tracking
    default-topic: doc-topic