spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trial
    username: docker
    password: docker
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

axon:
  axonserver:
    enabled: false
  kafka:
    bootstrap-servers: localhost:9094
